[config]

[freqs.analyze]
delta_t_ms = 20
freq_step = 2

[freqs.bistable]
input_bound = [0.005, 5.0]
lowpass = 1.5
lowpass_order = 3

[scales.analyze]
scales_cycoct = [0.5,1.0,2.0,4.0,8.0]
bandonly = true

[scales.bistable]
input_bound = [0.005, 0.1]
lowpass = 1.5
lowpass_order = 3

[rates]
rates_Hz = [2, 4, 8, 16, 32]
freq_limits_Hz = [400.0, 1200.0]
bandonly = true

[nmf]
ncomponents = 3
window_ms = 100
delta_ms = 75
skipframes = 0
maxiter = 100
tol = 1e-3

[track]
buildup_time_s = 2.0

[track.analyze]
time_constants_s = [4.0,8.0,16.0] # TODO: IF I KEEP THIS, CHANGE cortmi.jl!!!
max_sources = 3
unmodeled_prior = 0
# source_prior_sds = [0.01,0.035,0.12,0.4,1.5,5.0,6.0,7.5,10.0]
source_prior_sds = [2.0,4.0,6.0,8.0]
source_prior_N = 4
freq_prior_bias = 0
freq_prior_N = 2

[track.bistable]
input_bound = [0.0, 0.75]
lowpass = 1.5
lowpass_order = 3

[percept_lengths]
window_ms = 500
delta_ms = 250
min_length_ms = 750
threshold = 2.1
bandwidth_threshold = 0.25

